# This file was generated by setup.py

# Type this command to ignore changes to this file:
#   git update-index --assume-unchanged src/compile_time_constants.pxi

DEF UNAME_SYSNAME = "Windows"
cdef extern from "limits.h":
    cdef int INT_MIN
    cdef int INT_MAX
